# Generated by Django 5.2.12 on 2026-04-03 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('url_video', models.URLField(help_text='URL do vídeo (ex: YouTube ou Vimeo)')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição da aula')),
            ],
            options={
                'ordering': ['ordem', 'data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='AlunoCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ativo', models.BooleanField(default=False)),
                ('id_assinatura', models.CharField(blank=True, help_text='ID do assinante no Mercado Pago', max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
